### ISSUE TITLE
请问“选择文件”的按钮的前端代码写在哪个文件里了

### ISSUE THREAD

**Issue by xuzhushiqingbo** [kaiqiangren/VueExpress#1]
请问“选择文件”的按钮的前端代码写在哪个文件里了
![57e3b6f3-0cdf-45b8-9320-da973dcf16d1](https://user-images.githubusercontent.com/45909801/50050514-56f1e300-0138-11e9-8066-201565ea714a.png)

**Comment by kaiqiangren** [comment]
src/pages/index.vue
